[build]
publish = "public"
command = "./netlify-build.sh"

[build.environment]
NODE_VERSION = "16"
ANTORA_CACHE_DIR = "node_modules/.cache/antora"

[context.deploy-preview]
command = "URL=$DEPLOY_PRIME_URL ./netlify-build.sh"

[context.production.environment]
ALGOLIA_APP_ID = "Z8A024I0F5"
ALGOLIA_API_KEY = "1bd499249ebdef18e65f369e88597893"
ALGOLIA_IDX_NAME = "kroki-docs"

[[headers]]
for = "/_/font/*"
  [headers.values]
  Cache-Control = "public,max-age=604800"
