name: Site Indexer
on:
  workflow_dispatch:
  repository_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    container: algolia/docsearch-scraper:v1.16.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Index
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APP_ID }}
          API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          CONFIG: ${{ github.workspace }}/docsearch/config.json
        run: |
          INDEX_NAME=$(node -p "JSON.parse(require('fs').readFileSync('$CONFIG')).index_name")
          export HOME=/root
          export INDEX_NAME_TMP=$INDEX_NAME_tmp-$GITHUB_RUN_ID
          cd $HOME
          pipenv run python -m src.index
